version: "3.8"

services:
  # Banco de Dados que você já usa
  postgres:
    image: docker.io/library/postgres:16-alpine # É bom usar o caminho completo no Podman
    environment:
      POSTGRES_USER: restaurante_user
      POSTGRES_PASSWORD: restaurante_password
      POSTGRES_DB: restaurante_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z # O ':Z' configura os volumes para o SELinux, boa prática no Podman
      - ./enums.sql:/docker-entrypoint-initdb.d/enums.sql:Z
    networks:
      - restaurante_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U restaurante_user -d restaurante_db"]
      interval: 3s
      timeout: 3s
      retries: 3

  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Seu login no pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # Sua senha no pgAdmin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8081:80" # Acesse no navegador via localhost:8080
    volumes:
      - pgadmin_data:/var/lib/pgadmin:Z # Persiste as configurações do pgAdmin
    user: "5050:5050" # Evita erro de permissão (ID padrão do pgAdmin)
    networks:
      - restaurante_net
    depends_on:
      - postgres

  # Motor de Busca e Armazenamento de Logs
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false # Desativado apenas para facilitar o dev local
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Limita o uso de RAM no seu NixOS
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data:Z

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.12.0
  #   ports:
  #     - "5601:5601"
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:8.12.0
  #   user: root # Necessário para ler os logs do Docker no host
  #   volumes:
  #     - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
  #     - /home/doctor/.local/share/containers/storage:/var/log/podman:ro
  #     # Mapeia o socket do docker para coletar metadados (como o nome do container)
  #     - /nix/store/1y9yqcgynsi97sb17was2rfw53048nf7-podman-5.8.2/lib/systemd/system/podman.socket:/var/run/docker.sock:ro
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  #   depends_on:
  #     - elasticsearch

  # Futuro Broker de Mensageria (já estruturado)
  # rabbitmq:
  #   image: docker.io/library/rabbitmq:3.12-management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   volumes:
  #     - rabbitdata:/var/lib/rabbitmq:Z

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile # Dockerfile focado em produção (multistage)
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=restaurante_user
      - DB_NAME=restaurante_db
      - DB_SSL=disable
      - DB_PASS=restaurante_password
      # - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      # - ENV=production
    depends_on:
      - postgres
      # - rabbitmq
    logging:
      driver: "json-file" # garante o formato json padrão do docker
      options:
        max-size: "10m" # evita que o disco lote
        max-file: "3"

volumes:
  pgdata:
  pgadmin_data:
  # esdata:
  # rabbitdata:

networks:
  restaurante_net:
